### ISSUE TITLE
CI Pipeline

### ISSUE THREAD

**Issue by BaeKY** [BaeKY/svelte-hello-world#1]
## 개요
- 매번 로컬에서 [docker-push.sh](https://github.com/BaeKY/svelte-hello-world/blob/master/scripts/docker-push.sh)를 실행하여 container를 업데이트 하기보다는 push 하였을 때 자동으로 ghcr에 이미지가 업로드 되도록 한다.

## CI 
- [ ] [Gitlab CI](https://docs.gitlab.com/ee/ci/)
- [ ] [Github Actions](https://github.com/features/actions)

**Comment by BaeKY** [comment]
![k8s-cicd-App CI Flow drawio](https://user-images.githubusercontent.com/20514503/141686168-100e878e-4568-4204-b22b-1b70e9a8f11d.png)

## TODO
- [ ] Initialize git-flow
- [ ] Add Branch Protection Rules => [See here](https://cupjoo.tistory.com/11)
- [ ] Setup CI Pipeline
